### ISSUE TITLE
Problem with setting environment variable $BIOBAKERY_WORKFLOWS_DATABASES

### ISSUE THREAD

**Issue by gssin20** [biobakery/biobakery_workflows#15]
Hi 

I have been trying to install the environment variable BIOBAKERY WORKFLOWS with pip (https://github.com/biobakery/biobakery_workflows/wiki/Installing-the-workflows-with-pip) and then BIOBAKERY WORKFLOWS DATABASES using $ biobakery_workflows_databases --install --wmgx. Afetr solving for many errors, I have now hit the wall in the form of "setting environment variable $BIOBAKERY_WORKFLOWS_DATABASES"

As suggested in "Installing the workflows with pip" I have installed the workflows in a static environment: install_workflows. However, due to the disk space restrains from the univ management, the databases need to be installed at a custom location (in my case, it is /scratch/users/nus/saxena/miniconda3/envs/biobakery/opt/biobakery_workflows_databases). Now, for that I have set the environment variable by specifying 
"export BIOBAKERY_WORKFLOWS_DATABASES=/scratch/users/nus/saxena/miniconda3/envs/biobakery/opt/biobakery_workflows_databases" in .bashrc file. However, I am still getting the error "A custom install location was selected. Please set the environment variable $BIOBAKERY_WORKFLOWS_DATABASES to the install location."

Requesting your help

Regards
Gourvendu

![Env_Var_err](https://user-images.githubusercontent.com/8615618/124384474-ffbaba80-dd03-11eb-8d03-f6c79f30c265.png)
![Exp_var](https://user-images.githubusercontent.com/8615618/124384476-01847e00-dd04-11eb-9130-8112e96544d4.png)

**Comment by ljmciver** [comment]
Hi @gssin20 , Thank you for the detailed issue. The script always prints that warning message when a custom location is selected. The script does not first check to see if the environment variable `BIOBAKERY_WORKFLOWS_DATABASES` is set. If you have set that variable then please ignore the warning message. Sorry that message was confusing. Please post if you have any other issues.

Thank you,
Lauren
